In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
df = pd.read_csv("C:/Users/Lenovo/Downloads/diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
#데이터 로딩 
y=df['Outcome']
y.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [5]:
X=df.drop(columns=['Outcome'])
X.head

<bound method NDFrame.head of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]>

In [7]:
# 결측치 확인
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [13]:
#위에서부터 임신, 포도당, 혈압, 피부두께, 인슐린, BMI지수, 
#당뇨병 혈통함수(당뇨병을 앓은 혈연), 나이, 결과
#결과는 Y(실제 값)
#나머지 결측치는 모두 제거하면 안됨. 따라서 평균값으로 대체. 
mean_Pregnancies = df['Pregnancies'].mean()
mean_Glucose = df['Glucose'].mean()
mean_BloodPressure = df['BloodPressure'].mean()
mean_SkinThickness  = df['SkinThickness'].mean()
mean_Insulin = df['Insulin'].mean()
mean_BMI = df['BMI'].mean()
mean_DiabetesPedigreeFunction = df['DiabetesPedigreeFunction'].mean()
mean_Age = df['Age'].mean()

In [14]:
df['Pregnancies'].fillna(mean_Pregnancies, inplace=True)
df['Glucose'].fillna(mean_Glucose, inplace=True)
df['BloodPressure'].fillna(mean_BloodPressure, inplace=True)
df['SkinThickness'].fillna(mean_SkinThickness, inplace=True)
df['Insulin'].fillna(mean_Insulin, inplace=True)
df['BMI'].fillna(mean_BMI, inplace=True)
df['DiabetesPedigreeFunction'].fillna(mean_DiabetesPedigreeFunction, inplace=True)
df['Age'].fillna(mean_Age, inplace=True)
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [15]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [18]:
#인슐린, BMI, 포도당, 혈압, 피부두께(굳기?)는 0이 될 수 없음. 
#따라서 0인 행을 outlier로 인식하고 제거

columns_with_outliers = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df = df[(df[columns_with_outliers] != 0).all(axis=1)]
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
13,1,189,60,23,846,30.1,0.398,59,1
...,...,...,...,...,...,...,...,...,...
753,0,181,88,44,510,43.3,0.222,26,1
755,1,128,88,39,110,36.5,1.057,37,1
760,2,88,58,26,16,28.4,0.766,22,0
763,10,101,76,48,180,32.9,0.171,63,0
765,5,121,72,23,112,26.2,0.245,30,0

In [23]:
#인덱스 리셋
from sklearn.preprocessing import StandardScaler
df.reset_index(drop=True, inplace=True)

In [25]:
# 스케일러 초기화
scaler = StandardScaler()
# 'Outcome' 열을 제외한 데이터 스케일링
scaled_features = scaler.fit_transform(df.drop('Outcome', axis=1))

In [29]:
# 스케일된 데이터를 DataFrame으로 변환
scaled_df = pd.DataFrame(scaled_features, columns=df.columns[:-1])

# 'Outcome' 열 추가
scaled_df['Outcome'] = df['Outcome'].values

In [30]:
scaled_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,-0.717427,-1.091046,-0.373655,-0.585110,-0.522842,-0.710421,-1.031876,-0.968299,0
1,-1.029213,0.466314,-2.456964,0.557421,0.100631,1.426730,5.115111,0.209585,1
2,-0.093854,-1.447941,-1.655691,0.271788,-0.573394,-0.297238,-0.797126,-0.477514,1
3,-0.405640,2.413014,-0.053146,1.509530,3.260122,-0.368477,-1.057960,2.172726,1
4,-0.717427,2.153454,-0.854419,-0.585110,5.812990,-0.425468,-0.362402,2.761668,1
...,...,...,...,...,...,...,...,...,...
387,-1.029213,1.893894,1.389146,1.414319,2.982087,1.455225,-0.872478,-0.477514,1
388,-0.717427,0.174309,1.389146,0.938264,-0.388037,0.486384,1.547482,0.602213,1
389,-0.405640,-1.123491,-1.014673,-0.299477,-1.180016,-0.667678,0.704119,-0.870142,0
390,2.088650,-0.701706,0.427618,1.795162,0.201735,-0.026533,-1.020284,3.154296,0
391,0.529718,-0.052806,0.107109,-0.585110,-0.371186,-0.981127,-0.805820,-0.084886,0